version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: final
    restart: unless-stopped
    volumes:
      - ./output/Mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=final
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
# 접속 명령어
# docker exec -it deepfake_db mysql -u root -p
# 1234
